name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to Server 
      run: |
        ssh -o "StrictHostKeyChecking=no" ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          cd /root/cicd
          git pull
          docker build -t my-app .
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name my-app -p 80:3000 my-app
        EOF

        
